# for customizing
# ---input--------------------------------------------------------------------
# location of pod5 (sequencing data)
# used in dorado_basecall
reads_dir: ""
# "/scratch/kochsl99/ONT/data_amplicons2/pod5"
# "/home/leonie/projects/testNanopore/data/pod5"
# "/scratch/{USER}/ONT/data_amplicons2/pod5"

# optional
# If you want to START from already demuxed FASTQs instead (skip dorado),
# set this to the directory containing barcode01, barcode02, ...
# and DON'T run the dorado rules.
demux_fastq_dir: "/scratch/kochsl99/ONT/data_amplicons1/dorado/fastq_pass/merged"   # leave empty if you want the workflow to create its own demux dir

# ---outputs--------------------------------------------------------------------
# base ouput root
output_dir: "/scratch/kochsl99/ONT/data_amplicons1_snakemake"

# optional
# used in dereplicting
trimmed_fastq_dir: ""

# ---dorado--------------------------------------------------------------------
# choose the quality for the dorado run
# dna_r10.4.1_e8.2_400bps_fast -> fast, low accuracy
# dna_r10.4.1_e8.2_400bps_hac  -> high accuracy
# dna_r10.4.1_e8.2_400bps_sup  -> super accuracy
model: "dna_r10.4.1_e8.2_400bps_sup@v5.2.0"

# path to dorado software (needs to be installed)
dorado_software: "/home/kochsl99/software/dorado/dorado-1.2.0-linux-x64/bin/dorado"
# "/home/leonie/software/dorado/dorado-1.2.0-linux-x64/bin/dorado"
# "/home/kochsl99/software/dorado/dorado-1.2.0-linux-x64/bin/dorado"

# flowcell / kit type
kit: "SQK-NBD114-24"

# ---primers--------------------------------------------------------------------
primer_sets:
  set1:
    name: "515FY-926R"
    fwd: "GTGYCAGCMGCCGCGGTAA"  # Y = [CT] (pyrimidine)
    rev: "CCGYCAATTYMTTTRAGTTT" # M = [AT] (amino) R = [AG] (purine)
    minlen: 200
    maxlen: 450
    # barcode01, barcode 02, ...
    barcodes: ["01","02","03","04","05","06","07"] # for amplicons1
    
  set2:
    name: "DIV4_P5-P7"
    fwd: "GCGGTAATTCCAGCTCCAATAG"
    rev: "CTCTGACAATGGAATACGAATA"
    minlen: 200
    maxlen: 450
    barcodes: ["08","09","10","11","12","13","14","15","16","17","18","19","20","21","22","23"] # for amplicons1
